export const mockInbox = [
    {
      profileImageUrl: "/demo.png",
      firstName: "Alex",
      lastName: "Jones",
      email: "AlexJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 0,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Eric",
      lastName: "Xavier",
      email: "EricXavier@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 1,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 2,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 3,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 4,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 5,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 6,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 7,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 8,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 9,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 10,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 11,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 12,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 13,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 14,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 15,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 16,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 17,
    },
    {
      profileImageUrl: "/demo.png",
      firstName: "Johnny",
      lastName: "Jones",
      email: "JohnnyJones@gmail.com",
      recievedMessages: [],
      sentMessages: ["Hey! I'm reaching out to let you know that I have plenty of available dates for appointments.", "Feel free to reach out to me with any problems you're having."],
      latestMessage: {
        text: "Feel free to reach out to me with any problems you're having.",
        time: new Date(),
      },
      unreadMessages: 2,
      id: 18,
    },
  ];